name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: Run golangci lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
