name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
      pull-requests: read
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Unit Test
        id: unit_test
        run: gotestsum --format short-verbose ./...
